//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        public static string AddFilesBtnText {
            get {
                return ResourceManager.GetString("AddFilesBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a question template and create a question.
        /// </summary>
        public static string AddQuestionBtnDesc {
            get {
                return ResourceManager.GetString("AddQuestionBtnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new question.
        /// </summary>
        public static string AddQuestionBtnText {
            get {
                return ResourceManager.GetString("AddQuestionBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string AlignmentLabel {
            get {
                return ResourceManager.GetString("AlignmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string AnyText {
            get {
                return ResourceManager.GetString("AnyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on.
        /// </summary>
        public static string BasedOnLabel {
            get {
                return ResourceManager.GetString("BasedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        public static string ChooseQuestionTypeText {
            get {
                return ResourceManager.GetString("ChooseQuestionTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateBtnText {
            get {
                return ResourceManager.GetString("CreateBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if a style with the specified properties exists in the document.
        /// </summary>
        public static string CreateStyleQuestionDesc {
            get {
                return ResourceManager.GetString("CreateStyleQuestionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Word style.
        /// </summary>
        public static string CreateStyleQuestionName {
            get {
                return ResourceManager.GetString("CreateStyleQuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file?.
        /// </summary>
        public static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file.
        /// </summary>
        public static string ErrorOpeningFilename {
            get {
                return ResourceManager.GetString("ErrorOpeningFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string EvaluateBtnText {
            get {
                return ResourceManager.GetString("EvaluateBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FilesLabel {
            get {
                return ResourceManager.GetString("FilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font name.
        /// </summary>
        public static string FontNameLabel {
            get {
                return ResourceManager.GetString("FontNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a local question file.
        /// </summary>
        public static string ImportQuestionBtnDesc {
            get {
                return ResourceManager.GetString("ImportQuestionBtnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import question.
        /// </summary>
        public static string ImportQuestionBtnText {
            get {
                return ResourceManager.GetString("ImportQuestionBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format: malformed file.
        /// </summary>
        public static string InvalidFileFormatMsg {
            get {
                return ResourceManager.GetString("InvalidFileFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required fields are missing..
        /// </summary>
        public static string MissingRequiredFields {
            get {
                return ResourceManager.GetString("MissingRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New question.
        /// </summary>
        public static string NewQuestionTab {
            get {
                return ResourceManager.GetString("NewQuestionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files selected.
        /// </summary>
        public static string NoFilesSelected {
            get {
                return ResourceManager.GetString("NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this file.
        /// </summary>
        public static string NoPermissionDesc {
            get {
                return ResourceManager.GetString("NoPermissionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file.
        /// </summary>
        public static string OGFileLabel {
            get {
                return ResourceManager.GetString("OGFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question description.
        /// </summary>
        public static string QuestionDescLabel {
            get {
                return ResourceManager.GetString("QuestionDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question name.
        /// </summary>
        public static string QuestionNameLabel {
            get {
                return ResourceManager.GetString("QuestionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your questions.
        /// </summary>
        public static string QuestionsTab {
            get {
                return ResourceManager.GetString("QuestionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recents.
        /// </summary>
        public static string RecentText {
            get {
                return ResourceManager.GetString("RecentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question evaluation.
        /// </summary>
        public static string ResultsTab {
            get {
                return ResourceManager.GetString("ResultsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style name.
        /// </summary>
        public static string StyleNameLabel {
            get {
                return ResourceManager.GetString("StyleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove question from the list.
        /// </summary>
        public static string ToolTipRemoveButton {
            get {
                return ResourceManager.GetString("ToolTipRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the file.
        /// </summary>
        public static string UnableToAccessFile {
            get {
                return ResourceManager.GetString("UnableToAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open question.
        /// </summary>
        public static string UnableToOpenQuestion {
            get {
                return ResourceManager.GetString("UnableToOpenQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already tracked.
        /// </summary>
        public static string UnableToOpenQuestionDesc {
            get {
                return ResourceManager.GetString("UnableToOpenQuestionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
