name: Build and Release Avalonia App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for MacOS, Linux and Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Dependencies
      run: dotnet restore

    - name: Publish Application
      run: |
        dotnet publish -c Release -r ${{ matrix.os }}-${{ matrix.arch }} --self-contained -o publish/${{ matrix.os }}

    - name: Archive Build Artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: fileQuestionAssistant-${{ matrix.os }}-${{ matrix.arch }}
        path: publish/${{ matrix.os }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: fileQuestionAssistant-ubuntu-latest-x64
        path: ./artifacts/linux
    - name: Download macOS Artifact
      uses: actions/download-artifact@v3
      with:
        name: fileQuestionAssistant-macos-latest-x64
        path: ./artifacts/macos
    - name: Download Windows Artifact
      uses: actions/download-artifact@v3
      with:
        name: fileQuestionAssistant-windows-latest-x64
        path: ./artifacts/windows
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          ./artifacts/linux/*
          ./artifacts/macos/*
          ./artifacts/windows/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ github.run_number }}
        releaseName: File Question Assistant Release
        body: |
          ## Release Notes
          This release contains the following builds:
          - Windows
          - macOS
          - Linux
